sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  hipchat:
    rooms:
      - yDNjznYnlORISR3FkaRAs0p4kaj4n1aeGZCyhO0E@3787902
    on_success: never
    on_failure: change
    template:
      - '<a href="%{build_url}">%{repository}#%{build_number}</a> (%{author}: <a href="%{compare_url}">%{branch} - %{commit_subject}</a>): %{message}'
    format: html
    notify: true
deploy:
  provider: npm
  email: "awsudo.opensource@meltwater.com"
  api_key: "${NPM_DEPLOY_TOKEN}"
  on:
    tags: true
    only:
      - /^v\d+\.\d+\.\d+$/
  provider: script
  script: DOCKER_TAG=${TRAVIS_TAG} npm run deploy-docker
  on:
    tags: true
    only:
      - /^v\d+\.\d+\.\d+$/
